
services:
    db:
        image: mariadb:latest
        container_name: 'database'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: kuzelna
        ports:
            -   "3306:3306"
        networks:
            - app_network
        volumes:
            - db_data:/var/lib/mysql
    adminer:
        image: adminer:latest
        ports:
            -   "8080:8080"
        networks:
            - app_network
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
        driver: local
networks:
    app_network:
        driver: bridge

